DEFAULT:
  seed: 42
  savedir: ./results
  exp_name: '.'

DATASET:
  datadir: ../Data
  batch_size: 32
  test_batch_size: 16
  num_workers: 0
  dataset_name: MVTecAD  # [AnomalyDataset,MVTecAD]
  aug_info: 
    - Resize
  img_size: 224
  params:
    anomaly_ratio: 0.0
    baseline: True
  class_names:
    -
      - grid
      - carpet
      - cable
      - zipper
      - wood
      - tile
      - metal_nut
      - transistor
      - bottle
      - leather
      - pill
      - hazelnut
      - toothbrush
      - capsule
    - screw


OPTIMIZER:
  opt_name: Adam
  lr: 0.0005
  params:
    betas: 
    - 0.5
    - 0.999

TRAIN:
  epochs: 10
  grad_accum_steps: 1
  mixed_precision: 'no'
  log_interval: 100
  eval_interval: 1
  wandb:
    use: true
    project_name: CFGCAD
    
    
CONTINUAL:
  continual : True
  online: false
  method: 
    name: EMPTY

SCHEDULER: 
  name: null
  params: null

