DEFAULT:
  seed: 0
  savedir: ./results
  exp_name: '.'

DATASET:
  datadir: ../Data
  batch_size: 128
  test_batch_size: 32
  num_workers: 0
  dataset_name: MVTecAD  # [AnomalyDataset,MVTecAD]
  aug_info: 
    - Resize
  img_size: 224
  params:
    anomaly_ratio: 0.0
    baseline: True
  class_names:
    - grid
    - carpet
    - cable
    - zipper
    - wood
    - tile
    - metal_nut
    - transistor
    - bottle
    - leather
    - pill
    - hazelnut
    - toothbrush
    - capsule
    - screw


OPTIMIZER:
  opt_name: Adam
  lr: 0.005
  params:
    betas: 
    - 0.5
    - 0.999

TRAIN:
  epochs: 1
  grad_accum_steps: 1
  mixed_precision: 'no'
  log_interval: 1
  wandb:
    use: false
    project_name: LANGCAD
    
SCHEDULER: 
  name: null
  params: null
    
CONTINUAL:
  online: False 
  unified: False
  init_data_ratio: 1
  nb_tasks: 1