DEFAULT:
  seed: 0
  savedir: ./results
  exp_name: 'Baseline_pcb1&mara1_first'

DATASET:
  datadir: ../Data
  batch_size: 32
  test_batch_size: 32
  num_workers: 0
  dataset_name: VISA  # [AnomalyDataset,MVTecAD]
  aug_info: 
    - Resize
  img_size: 224
  params:
    anomaly_ratio: 0.0
    baseline: True
  class_names:
    - macaroni1
    - pcb1
    - candle
    - capsules
    - cashew
    - chewinggum
    - fryum
    - macaroni2
    - pcb2
    - pcb3
    - pcb4
    - pipe_fryum

OPTIMIZER:
  opt_name: Adam
  lr: 0.005
  params:
    betas: 
    - 0.5
    - 0.999

TRAIN:
  epochs: 1
  grad_accum_steps: 1
  mixed_precision: 'no'
  log_interval: 10
  wandb:
    use: false
    project_name: LANGCAD
    
SCHEDULER: 
  name: null
  params: null
    
