OPTIMIZER:
  opt_name: AdamW
  lr: 0.001
  params:
    betas: [0.9, 0.999]
    weight_decay: 0.0001

TRAIN:
  epochs: 100
  mixed_precision: 'no'
    
SCHEDULER:
  name: CyclicLR
  params:
    base_lr: 0.0001
    max_lr: 0.0005
    step_size_up: 20
    mode: exp_range
    gamma: 0.995

MODEL:
  method : CFGCAD
  backbone : None 
  params: 
    criterion_cfg:        
        - name: FeatureMSELoss
          type: FeatureMSELoss
          kwargs:
            weight: 1.0
        - name: CELoss
          type: CELoss
          kwargs: {}
        - name: SVDLoss
          type: SVDLoss
          kwargs: {}
    net_cfg:
        - name: backbone
          type: models.cfgcad.backbones.efficientnet_b4
          frozen: True
          kwargs:
            pretrained: True
            # select outlayers from: resnet [1,2,3,4], efficientnet [1,2,3,4,5]
            # empirically, for industrial: resnet [1,2,3] or [2,3], efficientnet [1,2,3,4] or [2,3,4]
            outlayers: [1,2,3,4]
        - name: neck
          prev: backbone
          type: models.cfgcad.necks.MFCN
          kwargs:
            outstrides: [16]
        - name: reconstruction
          prev: neck
          type: models.cfgcad.reconstructions.CFGReconstruction
          kwargs: 
            pos_embed_type: learned
            hidden_dim: 256
            nhead: 8
            num_encoder_layers: 4
            num_decoder_layers: 4
            dim_feedforward: 1024
            dropout: 0.1
            activation: relu
            normalize_before: False
            feature_jitter:
              scale: 20.0
              prob: 1.0
            neighbor_mask:
              neighbor_size: [7,7]
              mask: [False, False, False] # whether use mask in [enc, dec1, dec2]
            save_recon:
              save_dir: result_recon
            initializer:
              method: xavier_uniform
            cfg_embed_dim: 128
            uncond_prob: 0.1
            guidance_scale: 7.5
            feature_dim: 256 
    