DEFAULT:
  exp_name: 'test-all-continual-scheduler'
  description: ''

MODEL:
  method: LANGCAD
  backbone:
    name: ViT-B-16
    pretrained: openai #openai
  params:
    input_shape:
      - 3 
      - 224
      - 224
    faiss_num_workers: 4
    num_layers: 3
    sampling_ratio: 0.1
    num_prompts: 6
    prompt_dim: 768
    prompt_method: intermediate # intermediate input null
    txt_emb_method: null #null:last intermediate
    pre_task: null #margin infonce null 


DATASET:
  aug_info: 
    - PatchCore



OPTIMIZER:
  opt_name: Adam
  lr: 0.005
  params:
    betas:
    - 0.5
    - 0.999

SCHEDULER:
  name: CosineAnnealingWarmRestarts
  params:
    T_0: 5
    T_mult: 1
    eta_min: 0.0005

# SCHEDULER:
#   name: StepLR
#   params:
#     step_size: 10
#     gamma: 0.9

TRAIN:
  epochs: 400