DEFAULT:
  exp_name: 'kiie_method1100_memorybank_0001'
  description: 'Memory Bank 극한까지 줄였을 때 테스트'

MODEL:
  method: LANGCAD
  backbone:
    name: ViT-B-16
    pretrained: openai
  params:
    input_shape:
      - 3 
      - 224
      - 224
    faiss_num_workers: 4
    num_layers: 
      - 3
    sampling_ratio: 0.1
    num_prompts: 6


DATASET:
  aug_info: 
    - PatchCore


OPTIMIZER:
  opt_name: Adam
  lr: 0.005
  params:
    betas: 
    - 0.5
    - 0.999

TRAIN:
  epochs: 100