DEFAULT:
  exp_name: 'kiie_method301_cvit_prompt_pseudotext_priortaskneg'
  description: 'cvit - prompt - lang with pre created text using gpt4o with contrasitve learning using prior task'

MODEL:
  method: LANGCAD
  backbone:
    # name: ViT-B-32
    # pretrained: laion400m_e31
    name: ViT-B-16
    pretrained: openai
  params:
    input_shape:
      - 3 
      - 224
      - 224
    faiss_num_workers: 4
    num_layers: 
      - 3
    sampling_ratio: 0.1


DATASET:
  aug_info: 
    - PatchCore


OPTIMIZER:
  opt_name: Adam
  lr: 0.005
  params:
    betas: 
    - 0.5
    - 0.999

TRAIN:
  epochs: 100
