MODEL:
  method: PatchCore
  backbone: wide_resnet50_2
  params:
    input_shape:
      - 3 
      - 256
      - 256
    faiss_on_gpu: True
    faiss_num_workers: 4
    weight_method: identity # identity lof nearest gaussian
    threshold: quant_1
    sampling_ratio: 0.1

DATASET:
  aug_info: 
    - PatchCore